version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
